
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 05 00:31:43 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Link = 27;
  public static final int Numero_Decimal = 24;
  public static final int HEADER_FIN = 5;
  public static final int HTML_FIN = 3;
  public static final int HEADER_INICIO = 4;
  public static final int NOMBRE = 36;
  public static final int SIGNO_RESTA = 19;
  public static final int INTEGER = 46;
  public static final int DOS_PUNTOS = 39;
  public static final int ETIQUETA_COLUMNA = 31;
  public static final int ETIQUETA_ENLACE = 30;
  public static final int LIST_FIN = 14;
  public static final int IMAGE_INICIO = 15;
  public static final int Email = 25;
  public static final int TABLE_INICIO = 9;
  public static final int SIGNO_SUMA = 18;
  public static final int BODY_INICIO = 7;
  public static final int IMAGE_FIN = 16;
  public static final int BODY_FIN = 8;
  public static final int ETIQUETA_PRUEBA = 35;
  public static final int ETIQUETA_IMPRIMIR = 33;
  public static final int ROW_FIN = 12;
  public static final int LIST_INICIO = 13;
  public static final int AbreParentesis = 21;
  public static final int LISTA = 48;
  public static final int PUNTO_COMA = 41;
  public static final int SIGNO_MULTIPLICACION = 20;
  public static final int EOF = 0;
  public static final int COMILLA = 37;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int Titulo_Encabezado = 26;
  public static final int ROW_INICIO = 11;
  public static final int TABLE_FIN = 10;
  public static final int ETIQUETA_NEGRITA = 32;
  public static final int ETIQUETA_BORDE = 34;
  public static final int TITLE = 6;
  public static final int QUOT = 43;
  public static final int CierraParentesis = 22;
  public static final int HTML_INICIO = 2;
  public static final int ETIQUETA_ALTURA = 28;
  public static final int FLOAT = 47;
  public static final int Signo_Igual = 17;
  public static final int SIGNO_DIVISION = 44;
  public static final int STRING = 45;
  public static final int ETIQUETA_ANCHO = 29;
  public static final int IMAGEN_FOTO = 40;
  public static final int TEXTO = 38;
  public static final int Numero = 23;
}

